"""Simulador: usa pipeline.process() real con dry_run=True."""

import time
from pathlib import Path

import sqlalchemy as sa
from fastapi import APIRouter, Form, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.templating import Jinja2Templates

from app.admin.auth_utils import effective_tenant
from app.bot.pipeline import process
from app.db.session import async_session_factory

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"
templates = Jinja2Templates(directory=str(TEMPLATES_DIR))

router = APIRouter(prefix="/admin/simulate", tags=["admin-simulate"])


CHANNEL_OPTIONS = [
    ("simulator", "Simulador (por defecto)"),
    ("telegram", "Telegram"),
    ("whatsapp_official", "WhatsApp Oficial"),
    ("whatsapp_unofficial", "WhatsApp No Oficial"),
    ("webchat", "Webchat"),
]


@router.get("/", response_class=HTMLResponse)
async def simulate_ui(request: Request, tenant: str = "green-glamping"):
    tenant = effective_tenant(request, tenant)
    return templates.TemplateResponse(
        request, "simulate/index.html",
        {"tenant": tenant, "channel_options": CHANNEL_OPTIONS},
    )


@router.post("/", response_class=JSONResponse)
async def simulate(
    request: Request,
    tenant: str = Form("green-glamping"),
    thread_id: str = Form("sim-001"),
    message: str = Form(...),
    channel: str = Form("simulator"),
):
    tenant = effective_tenant(request, tenant)
    start = time.monotonic()

    async with async_session_factory() as session:
        tenant_row = (await session.execute(
            sa.text("SELECT id, operation_mode, bot_config FROM public.tenants WHERE slug = :s"),
            {"s": tenant},
        )).fetchone()
        if not tenant_row:
            return JSONResponse({"error": f"Tenant '{tenant}' not found"}, status_code=404)

        cfg = dict(tenant_row.bot_config or {})

        result = await process(
            text=message,
            tenant_id=tenant_row.id,
            session=session,
            external_thread_id=thread_id,
            user_external_id=f"sim-{tenant_row.id}",
            push_name="Admin Simulator",
            operation_mode=tenant_row.operation_mode or "autonomous",
            config=cfg,
            dry_run=True,
            _channel_override=channel,
        )

    total_ms = round((time.monotonic() - start) * 1000)
    trace = result.trace or []

    bubble_plan = []
    if not result.blocked_injection and result.outbound.text:
        try:
            from app.bot.humanizer import default_humanization, plan
            hz = cfg.get("humanization")
            if not isinstance(hz, dict):
                hz = default_humanization()
            for ch in (hz.get("channels") or []):
                plan_for_ch = plan(result.outbound.text or "", hz)
                if plan_for_ch:
                    bubble_plan.append({
                        "channel": ch,
                        "applies": hz.get("enabled", False),
                        "bubbles": [
                            {"i": i, "text": b.text, "typing_ms": b.typing_ms, "pause_before_ms": b.pause_before_ms}
                            for i, b in enumerate(plan_for_ch)
                        ],
                    })
        except Exception:
            bubble_plan = []

    return JSONResponse({
        "blocked": result.blocked_injection,
        "llm_calls": 1 if any(s["step"] == "llm_decision" and s["detail"].get("decision") == "llm_invoked" for s in trace) else 0,
        "total_ms": total_ms,
        "intent": result.outbound.intent_name,
        "response_preview": (result.outbound.text or "")[:300],
        "response_text": result.outbound.text,
        "media_attachments": result.outbound.media_attachments or [],
        "requires_human": result.outbound.requires_human,
        "handoff_rule": result.outbound.handoff_rule,
        "trace": trace,
        "bubble_plan": bubble_plan,
        "humanization_enabled": (cfg.get("humanization") or {}).get("enabled", False),
    })


@router.post("/export-test")
async def export_test(
    tenant: str = Form("green-glamping"),
    message: str = Form(...),
    expected_intent: str = Form(""),
):
    """Generate a pytest snippet for the given test case."""
    safe_msg = message.replace('"', '\\"').replace("\n", "\\n")
    code = f'''\
import pytest

@pytest.mark.asyncio
async def test_{(expected_intent or "message").replace("-","_")}():
    """Auto-generated by Multibot simulator."""
    from app.bot.classifier import classify
    # message: "{safe_msg}"
    class FakeSession:
        async def execute(self, *a, **kw):
            raise NotImplementedError("Offline test — mock the session")
    result = ...  # run offline using seed JSON as in tests/test_classifier.py
    assert result.intent_name == "{expected_intent}"
'''
    return JSONResponse({"code": code})